version: "3.8"
services:
  react-app: 
    image: react-app
    ports:
      - "3000:3000"

  api:
    image: 2peers-backend
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "127.0.0.1:5433:5432"
    volumes:
      - twopeers-db:/var/lib/postgresql/data

  twopeers:
    build:
      context: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: Theworst123
      DB_HOST: localhost
      DB_DATABASE: 2peers
    ports:
      - '8000:8000'
        
volumes:
  twopeers-db: