version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "127.0.0.1:5433:5432"
    volumes:
      - twopeers-db:/var/lib/postgresql/data

  twopeers:
    build:
      context: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: Theworst123
      DB_HOST: localhost
      DB_DATABASE: 2peers
    depends_on:
      - postgres
    ports:
      - '8000:8000'
        
volumes:
  twopeers-db: